### ISSUE TITLE
isAsyncRequest is false despite "four_labs_gamp.async_requests: true" is set in confing.yml

### ISSUE THREAD

**Issue by kestux** [fourlabsldn/GampBundle#14]
Hi,

During _XDEBUG_ session I've noticed that param `isAsyncRequest` is set to `false` in `TheIconic\Tracking\GoogleAnalytics\Analytics` instance.  I have to set `$analytics->setAsyncRequest(true)`, to set the param to `true`.

My _config.yml_:
```
four_labs_gamp:
    protocol_version: 1
    tracking_id: "%google.analytics.tracking.id%"
    use_ssl: true
    anonymize_ip: false
    async_requests: true
    sandbox: %google.analytics.is.sandbox%
```

Also I noticed that `async_requests` prop is defaulted to `true` in [FourLabs\GampBundle\DependencyInjection\Configuration::getConfigTreeBuilder()](https://github.com/fourlabsldn/GampBundle/blob/master/DependencyInjection/Configuration.php#L33) and I tried to remove is from my config, but the `isAsyncRequest` remained `false`. I think it must be something wrong with the setter.
